# Generated by Django 2.1.4 on 2018-12-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avdelning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avdelning_namn', models.CharField(max_length=255)),
                ('kostnadsställe', models.IntegerField()),
                ('lokal', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='inventarie',
            name='benämning',
            field=models.CharField(default='benämning', max_length=255),
        ),
        migrations.AddField(
            model_name='inventarie',
            name='avdelning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avdelning_inventarier_set', to='inventarier.Avdelning'),
        ),
        migrations.AddField(
            model_name='inventarie',
            name='ägare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ägare_inventarier_set', to='inventarier.Avdelning'),
        ),
    ]
