# Generated by Django 2.1.4 on 2018-12-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0002_auto_20181218_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarie',
            name='benämning',
            field=models.CharField(max_length=255),
        ),
    ]
