# Generated by Django 2.1.4 on 2018-12-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0003_auto_20181218_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarie',
            name='benämning',
        ),
        migrations.RemoveField(
            model_name='inventarie',
            name='modell',
        ),
        migrations.RemoveField(
            model_name='inventarie',
            name='tillverkare',
        ),
    ]
