# Generated by Django 2.1.4 on 2018-12-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0004_auto_20181218_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benämning', models.CharField(max_length=255)),
                ('tillverkare', models.CharField(max_length=255)),
                ('modell', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='inventarie',
            name='produkt',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventarier.Produkt'),
            preserve_default=False,
        ),
    ]
