# Generated by Django 2.1.4 on 2018-12-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0006_auto_20181218_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarie',
            options={'verbose_name_plural': 'Inventarier'},
        ),
        migrations.AlterField(
            model_name='inventarie',
            name='inventarie_nummer',
            field=models.IntegerField(unique=True),
        ),
    ]
