# Generated by Django 2.1.4 on 2018-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0007_auto_20181218_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarie',
            name='inventarie_nummer',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='inventarie',
            name='serienummer',
            field=models.CharField(max_length=100),
        ),
    ]
