# Generated by Django 2.1.4 on 2018-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0008_auto_20181219_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarie',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
