# Generated by Django 2.1.4 on 2018-12-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0009_inventarie_aktiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarieKommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skapades', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('inventarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarier.Inventarie')),
            ],
        ),
    ]
