# Generated by Django 2.1.4 on 2018-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0011_inventariekommentar_ämne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benämning', models.CharField(max_length=255)),
                ('tillverkare', models.CharField(max_length=255)),
                ('modell', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inventariekommentar',
            options={'verbose_name_plural': 'Inventarie kommentarer'},
        ),
    ]
