# Generated by Django 2.1.4 on 2018-12-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0012_auto_20181220_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkt',
            options={'verbose_name_plural': 'Produkter'},
        ),
        migrations.AddField(
            model_name='inventarie',
            name='produkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarier.Produkt'),
        ),
    ]
