# Generated by Django 2.1.4 on 2018-12-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0014_auto_20181220_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarie',
            name='avdelning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avdelning_inventarier_set', to='inventarier.Avdelning'),
        ),
        migrations.AddField(
            model_name='inventarie',
            name='utlånad_till',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lånade_inventarier_set', to='inventarier.Avdelning'),
        ),
    ]
