# Generated by Django 2.1.4 on 2018-12-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarier', '0015_auto_20181220_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avdelning',
            options={'verbose_name_plural': 'Avdelningar'},
        ),
        migrations.AlterField(
            model_name='inventarie',
            name='utlånad_till',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lånade_inventarier_set', to='inventarier.Avdelning'),
        ),
    ]
